In [1]:
import numpy as np
import pandas as pd

import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD

from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from openpyxl import Workbook

dataset = pd.read_csv("C:/Users/hp/Desktop/ML/cerebro/Lockdown Mania/coronaTrain.csv")
pred= pd.read_csv("C:/Users/hp/Desktop/ML/cerebro/Lockdown Mania/coronaTest.csv")


Using TensorFlow backend.


In [2]:
x_train=dataset.iloc[:,1:-1]
y_train=dataset.iloc[:,1001:]
x_test= pred.iloc[:,1:]

In [3]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)

print(y_train)


print(y_train.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
(1287, 3)


In [8]:
y_test= keras.utils.to_categorical(np.random.randint(3,size=(1332,1)),num_classes=3)
print(y_test)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [9]:
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=1000))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))



In [10]:

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [11]:
model.fit(x_train, y_train, epochs=6000, batch_size=64)

Epoch 1/6000
1287/1287 [==============================] - 0s 259us/step - loss: 6.5622 - accuracy: 0.5659
Epoch 2/6000
1287/1287 [==============================] - 0s 78us/step - loss: 6.3287 - accuracy: 0.5856
Epoch 3/6000
1287/1287 [==============================] - 0s 78us/step - loss: 6.1845 - accuracy: 0.5944
Epoch 4/6000
1287/1287 [==============================] - 0s 77us/step - loss: 6.0738 - accuracy: 0.6017
Epoch 5/6000
1287/1287 [==============================] - 0s 72us/step - loss: 5.7023 - accuracy: 0.6255
Epoch 6/6000
1287/1287 [==============================] - 0s 79us/step - loss: 5.3288 - accuracy: 0.6493
Epoch 7/6000
1287/1287 [==============================] - 0s 78us/step - loss: 4.9769 - accuracy: 0.6716
Epoch 8/6000
1287/1287 [==============================] - 0s 80us/step - loss: 4.4941 - accuracy: 0.7037
Epoch 9/6000
1287/1287 [==============================] - 0s 102us/step - loss: 4.0476 - accuracy: 0.7301
Epoch 10/6000
1287/1287 [============================

1287/1287 [==============================] - 0s 111us/step - loss: 0.9494 - accuracy: 0.9373
Epoch 78/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.9227 - accuracy: 0.9376
Epoch 79/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.8528 - accuracy: 0.9435
Epoch 80/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.9257 - accuracy: 0.9391
Epoch 81/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.9035 - accuracy: 0.9409
Epoch 82/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.8105 - accuracy: 0.9466
Epoch 83/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.9504 - accuracy: 0.9376
Epoch 84/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.8377 - accuracy: 0.9438
Epoch 85/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.8945 - accuracy: 0.9407
Epoch 86/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 127us/step - loss: 0.5890 - accuracy: 0.9617
Epoch 154/6000
1287/1287 [==============================] - 0s 116us/step - loss: 0.5610 - accuracy: 0.9627
Epoch 155/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.5691 - accuracy: 0.9627
Epoch 156/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.5721 - accuracy: 0.9622
Epoch 157/6000
1287/1287 [==============================] - 0s 135us/step - loss: 0.5233 - accuracy: 0.9648
Epoch 158/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.5352 - accuracy: 0.9643
Epoch 159/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.5035 - accuracy: 0.9661
Epoch 160/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.5480 - accuracy: 0.9627
Epoch 161/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.5108 - accuracy: 0.9650
Epoch 162/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 112us/step - loss: 0.5045 - accuracy: 0.9661
Epoch 230/6000
1287/1287 [==============================] - 0s 124us/step - loss: 0.4085 - accuracy: 0.9720
Epoch 231/6000
1287/1287 [==============================] - 0s 124us/step - loss: 0.4411 - accuracy: 0.9705
Epoch 232/6000
1287/1287 [==============================] - 0s 128us/step - loss: 0.3570 - accuracy: 0.9757
Epoch 233/6000
1287/1287 [==============================] - 0s 118us/step - loss: 0.4006 - accuracy: 0.9723
Epoch 234/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.3904 - accuracy: 0.9746
Epoch 235/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.4233 - accuracy: 0.9720
Epoch 236/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.3590 - accuracy: 0.9764
Epoch 237/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.4010 - accuracy: 0.9736
Epoch 238/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 111us/step - loss: 0.3790 - accuracy: 0.9746
Epoch 306/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.4204 - accuracy: 0.9715
Epoch 307/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.4039 - accuracy: 0.9731
Epoch 308/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.4360 - accuracy: 0.9700
Epoch 309/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.3733 - accuracy: 0.9751
Epoch 310/6000
1287/1287 [==============================] - 0s 104us/step - loss: 0.3192 - accuracy: 0.9788
Epoch 311/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.2947 - accuracy: 0.9795
Epoch 312/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.3406 - accuracy: 0.9767
Epoch 313/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.3553 - accuracy: 0.9759
Epoch 314/6000
1287/1287 [=================

Epoch 381/6000
1287/1287 [==============================] - 0s 120us/step - loss: 0.2569 - accuracy: 0.9824
Epoch 382/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.2676 - accuracy: 0.9824
Epoch 383/6000
1287/1287 [==============================] - 0s 105us/step - loss: 0.2973 - accuracy: 0.9798
Epoch 384/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.3046 - accuracy: 0.9782
Epoch 385/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.2610 - accuracy: 0.9829
Epoch 386/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.3001 - accuracy: 0.9798
Epoch 387/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.3619 - accuracy: 0.9757
Epoch 388/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.3035 - accuracy: 0.9788
Epoch 389/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.2878 - accuracy: 0.9808
Epoch 390/6000
1287/1287 [==

1287/1287 [==============================] - 0s 105us/step - loss: 0.2868 - accuracy: 0.9814
Epoch 457/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.2952 - accuracy: 0.9806
Epoch 458/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.2952 - accuracy: 0.9806
Epoch 459/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.2718 - accuracy: 0.9819
Epoch 460/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.3192 - accuracy: 0.9788
Epoch 461/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.3106 - accuracy: 0.9790
Epoch 462/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.3426 - accuracy: 0.9777
Epoch 463/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.3445 - accuracy: 0.9769
Epoch 464/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.2713 - accuracy: 0.9821
Epoch 465/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 72us/step - loss: 0.2344 - accuracy: 0.9837
Epoch 533/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2629 - accuracy: 0.9829
Epoch 534/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2396 - accuracy: 0.9842
Epoch 535/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2448 - accuracy: 0.9837
Epoch 536/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.2025 - accuracy: 0.9865
Epoch 537/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.2782 - accuracy: 0.9806
Epoch 538/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2485 - accuracy: 0.9829
Epoch 539/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2555 - accuracy: 0.9832
Epoch 540/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2686 - accuracy: 0.9814
Epoch 541/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 75us/step - loss: 0.2562 - accuracy: 0.9826
Epoch 609/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.2956 - accuracy: 0.9803
Epoch 610/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.2429 - accuracy: 0.9832
Epoch 611/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2555 - accuracy: 0.9832
Epoch 612/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2626 - accuracy: 0.9819
Epoch 613/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.2493 - accuracy: 0.9829
Epoch 614/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2315 - accuracy: 0.9847
Epoch 615/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1757 - accuracy: 0.9883
Epoch 616/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.2242 - accuracy: 0.9850
Epoch 617/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 71us/step - loss: 0.2549 - accuracy: 0.9834
Epoch 685/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2095 - accuracy: 0.9858
Epoch 686/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1535 - accuracy: 0.9891
Epoch 687/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1963 - accuracy: 0.9865
Epoch 688/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.2256 - accuracy: 0.9845
Epoch 689/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2394 - accuracy: 0.9842
Epoch 690/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1997 - accuracy: 0.9863
Epoch 691/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.2355 - accuracy: 0.9839
Epoch 692/6000
1287/1287 [==============================] - 0s 86us/step - loss: 0.2231 - accuracy: 0.9855
Epoch 693/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 75us/step - loss: 0.1917 - accuracy: 0.9873
Epoch 761/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2063 - accuracy: 0.9855
Epoch 762/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.2239 - accuracy: 0.9850
Epoch 763/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2120 - accuracy: 0.9845
Epoch 764/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.2074 - accuracy: 0.9865
Epoch 765/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.1613 - accuracy: 0.9886
Epoch 766/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.3049 - accuracy: 0.9793
Epoch 767/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2138 - accuracy: 0.9852
Epoch 768/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.2076 - accuracy: 0.9863
Epoch 769/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 74us/step - loss: 0.1868 - accuracy: 0.9873
Epoch 837/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1764 - accuracy: 0.9881
Epoch 838/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.2546 - accuracy: 0.9829
Epoch 839/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2430 - accuracy: 0.9839
Epoch 840/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.2191 - accuracy: 0.9850
Epoch 841/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.2162 - accuracy: 0.9852
Epoch 842/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1995 - accuracy: 0.9868
Epoch 843/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.1946 - accuracy: 0.9868
Epoch 844/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1753 - accuracy: 0.9886
Epoch 845/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 72us/step - loss: 0.1919 - accuracy: 0.9870
Epoch 913/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.1995 - accuracy: 0.9868
Epoch 914/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.2005 - accuracy: 0.9860
Epoch 915/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.1575 - accuracy: 0.9896
Epoch 916/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.1839 - accuracy: 0.9881
Epoch 917/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.1889 - accuracy: 0.9860
Epoch 918/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1525 - accuracy: 0.9896
Epoch 919/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.1832 - accuracy: 0.9881
Epoch 920/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.1597 - accuracy: 0.9896
Epoch 921/6000
1287/1287 [==========================

1287/1287 [==============================] - 0s 112us/step - loss: 0.1912 - accuracy: 0.9876
Epoch 989/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1835 - accuracy: 0.9881
Epoch 990/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1522 - accuracy: 0.9896
Epoch 991/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1756 - accuracy: 0.9886
Epoch 992/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1841 - accuracy: 0.9876
Epoch 993/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1600 - accuracy: 0.9891
Epoch 994/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.2226 - accuracy: 0.9855
Epoch 995/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1363 - accuracy: 0.9912
Epoch 996/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.2039 - accuracy: 0.9865
Epoch 997/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 110us/step - loss: 0.2072 - accuracy: 0.9865
Epoch 1064/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1280 - accuracy: 0.9912
Epoch 1065/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.2070 - accuracy: 0.9860
Epoch 1066/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1668 - accuracy: 0.9891
Epoch 1067/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1517 - accuracy: 0.9902
Epoch 1068/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1380 - accuracy: 0.9907
Epoch 1069/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1832 - accuracy: 0.9881
Epoch 1070/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1295 - accuracy: 0.9912
Epoch 1071/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1962 - accuracy: 0.9870
Epoch 1072/6000
1287/1287 [========

1287/1287 [==============================] - 0s 113us/step - loss: 0.1761 - accuracy: 0.9881
Epoch 1139/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1960 - accuracy: 0.9871
Epoch 1140/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1809 - accuracy: 0.9876
Epoch 1141/6000
1287/1287 [==============================] - 0s 105us/step - loss: 0.1670 - accuracy: 0.9891
Epoch 1142/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1514 - accuracy: 0.9902
Epoch 1143/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1940 - accuracy: 0.9865
Epoch 1144/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1599 - accuracy: 0.9891
Epoch 1145/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.2164 - accuracy: 0.9850
Epoch 1146/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.2234 - accuracy: 0.9855
Epoch 1147/6000
1287/1287 [========

1287/1287 [==============================] - 0s 109us/step - loss: 0.2083 - accuracy: 0.9860
Epoch 1214/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1445 - accuracy: 0.9902
Epoch 1215/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1690 - accuracy: 0.9881
Epoch 1216/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1360 - accuracy: 0.9907
Epoch 1217/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1822 - accuracy: 0.9876
Epoch 1218/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.0705 - accuracy: 0.9953
Epoch 1219/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1198 - accuracy: 0.9922
Epoch 1220/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.2000 - accuracy: 0.9865
Epoch 1221/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1212 - accuracy: 0.9912
Epoch 1222/6000
1287/1287 [========

1287/1287 [==============================] - 0s 118us/step - loss: 0.1291 - accuracy: 0.9907
Epoch 1289/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.2080 - accuracy: 0.9860
Epoch 1290/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1206 - accuracy: 0.9912
Epoch 1291/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1754 - accuracy: 0.9886
Epoch 1292/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1728 - accuracy: 0.9876
Epoch 1293/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1145 - accuracy: 0.9917
Epoch 1294/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1357 - accuracy: 0.9912
Epoch 1295/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1593 - accuracy: 0.9896
Epoch 1296/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1926 - accuracy: 0.9870
Epoch 1297/6000
1287/1287 [========

1287/1287 [==============================] - 0s 109us/step - loss: 0.1993 - accuracy: 0.9871
Epoch 1364/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1665 - accuracy: 0.9891
Epoch 1365/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1593 - accuracy: 0.9896
Epoch 1366/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1111 - accuracy: 0.9917
Epoch 1367/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1416 - accuracy: 0.9896
Epoch 1368/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1514 - accuracy: 0.9902
Epoch 1369/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1755 - accuracy: 0.9886
Epoch 1370/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1280 - accuracy: 0.9917
Epoch 1371/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1434 - accuracy: 0.9907
Epoch 1372/6000
1287/1287 [========

1287/1287 [==============================] - 0s 106us/step - loss: 0.1436 - accuracy: 0.9907
Epoch 1439/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.2231 - accuracy: 0.9855
Epoch 1440/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1221 - accuracy: 0.9917
Epoch 1441/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.1275 - accuracy: 0.9917
Epoch 1442/6000
1287/1287 [==============================] - 0s 95us/step - loss: 0.1570 - accuracy: 0.9896
Epoch 1443/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.1357 - accuracy: 0.9912
Epoch 1444/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.2443 - accuracy: 0.9839
Epoch 1445/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.1263 - accuracy: 0.9917
Epoch 1446/6000
1287/1287 [==============================] - 0s 118us/step - loss: 0.1754 - accuracy: 0.9881
Epoch 1447/6000
1287/1287 [==========

1287/1287 [==============================] - 0s 109us/step - loss: 0.1593 - accuracy: 0.9896
Epoch 1514/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1914 - accuracy: 0.9876
Epoch 1515/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1557 - accuracy: 0.9891
Epoch 1516/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1835 - accuracy: 0.9881
Epoch 1517/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1673 - accuracy: 0.9891
Epoch 1518/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1445 - accuracy: 0.9902
Epoch 1519/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1994 - accuracy: 0.9870
Epoch 1520/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1322 - accuracy: 0.9912
Epoch 1521/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1912 - accuracy: 0.9876
Epoch 1522/6000
1287/1287 [========

1287/1287 [==============================] - 0s 109us/step - loss: 0.1654 - accuracy: 0.9891
Epoch 1589/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1757 - accuracy: 0.9886
Epoch 1590/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1844 - accuracy: 0.9876
Epoch 1591/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1841 - accuracy: 0.9876
Epoch 1592/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.2071 - accuracy: 0.9865
Epoch 1593/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1759 - accuracy: 0.9881
Epoch 1594/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1985 - accuracy: 0.9865
Epoch 1595/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0849 - accuracy: 0.9938
Epoch 1596/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1124 - accuracy: 0.9927
Epoch 1597/6000
1287/1287 [========

1287/1287 [==============================] - 0s 106us/step - loss: 0.1717 - accuracy: 0.9886
Epoch 1664/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1691 - accuracy: 0.9886
Epoch 1665/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1118 - accuracy: 0.9917
Epoch 1666/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1849 - accuracy: 0.9871
Epoch 1667/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.1880 - accuracy: 0.9876
Epoch 1668/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1354 - accuracy: 0.9912
Epoch 1669/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1420 - accuracy: 0.9907
Epoch 1670/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1344 - accuracy: 0.9912
Epoch 1671/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1070 - accuracy: 0.9922
Epoch 1672/6000
1287/1287 [========

1287/1287 [==============================] - 0s 107us/step - loss: 0.0774 - accuracy: 0.9948
Epoch 1738/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1277 - accuracy: 0.9917
Epoch 1739/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0948 - accuracy: 0.9933
Epoch 1740/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1005 - accuracy: 0.9922
Epoch 1741/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1031 - accuracy: 0.9933
Epoch 1742/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0745 - accuracy: 0.9948
Epoch 1743/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1634 - accuracy: 0.9886
Epoch 1744/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1132 - accuracy: 0.9917
Epoch 1745/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1515 - accuracy: 0.9902
Epoch 1746/6000
1287/1287 [========

1287/1287 [==============================] - 0s 110us/step - loss: 0.2071 - accuracy: 0.9865
Epoch 1813/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1679 - accuracy: 0.9891
Epoch 1814/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1208 - accuracy: 0.9912
Epoch 1815/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1340 - accuracy: 0.9912
Epoch 1816/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1199 - accuracy: 0.9922
Epoch 1817/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0956 - accuracy: 0.9938
Epoch 1818/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1201 - accuracy: 0.9917
Epoch 1819/6000
1287/1287 [==============================] - 0s 160us/step - loss: 0.1198 - accuracy: 0.9912
Epoch 1820/6000
1287/1287 [==============================] - 0s 122us/step - loss: 0.1641 - accuracy: 0.9891
Epoch 1821/6000
1287/1287 [========

1287/1287 [==============================] - 0s 104us/step - loss: 0.0736 - accuracy: 0.9948
Epoch 1888/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.1356 - accuracy: 0.9912
Epoch 1889/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1358 - accuracy: 0.9912
Epoch 1890/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1356 - accuracy: 0.9912
Epoch 1891/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1131 - accuracy: 0.9917
Epoch 1892/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 1893/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1204 - accuracy: 0.9917
Epoch 1894/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1363 - accuracy: 0.9907
Epoch 1895/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 1896/6000
1287/1287 [========

1287/1287 [==============================] - 0s 107us/step - loss: 0.0878 - accuracy: 0.9943
Epoch 1963/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1512 - accuracy: 0.9896
Epoch 1964/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1115 - accuracy: 0.9927
Epoch 1965/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 1966/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 1967/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 1968/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.0637 - accuracy: 0.9959
Epoch 1969/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.0571 - accuracy: 0.9959
Epoch 1970/6000
1287/1287 [==============================] - 0s 104us/step - loss: 0.1427 - accuracy: 0.9907
Epoch 1971/6000
1287/1287 [========

1287/1287 [==============================] - 0s 113us/step - loss: 0.1122 - accuracy: 0.9922
Epoch 2038/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0800 - accuracy: 0.9943
Epoch 2039/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1516 - accuracy: 0.9902
Epoch 2040/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1042 - accuracy: 0.9927
Epoch 2041/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0808 - accuracy: 0.9943
Epoch 2042/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1036 - accuracy: 0.9933
Epoch 2043/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0890 - accuracy: 0.9938
Epoch 2044/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.1038 - accuracy: 0.9933
Epoch 2045/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1277 - accuracy: 0.9917
Epoch 2046/6000
1287/1287 [========

1287/1287 [==============================] - 0s 106us/step - loss: 0.0960 - accuracy: 0.9938
Epoch 2113/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0815 - accuracy: 0.9938
Epoch 2114/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.1058 - accuracy: 0.9927
Epoch 2115/6000
1287/1287 [==============================] - ETA: 0s - loss: 0.1613 - accuracy: 0.98 - 0s 110us/step - loss: 0.1443 - accuracy: 0.9902
Epoch 2116/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 2117/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1194 - accuracy: 0.9922
Epoch 2118/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0820 - accuracy: 0.9938
Epoch 2119/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0538 - accuracy: 0.9964
Epoch 2120/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0647 - accuracy: 

1287/1287 [==============================] - 0s 109us/step - loss: 0.1048 - accuracy: 0.9927
Epoch 2187/6000
1287/1287 [==============================] - 0s 116us/step - loss: 0.0888 - accuracy: 0.9938
Epoch 2188/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1106 - accuracy: 0.9927
Epoch 2189/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 2190/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1434 - accuracy: 0.9907
Epoch 2191/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.0647 - accuracy: 0.9953
Epoch 2192/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 2193/6000
1287/1287 [==============================] - 0s 91us/step - loss: 0.0967 - accuracy: 0.9933
Epoch 2194/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.1338 - accuracy: 0.9907
Epoch 2195/6000
1287/1287 [==========

1287/1287 [==============================] - 0s 70us/step - loss: 0.0958 - accuracy: 0.9927
Epoch 2262/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.1675 - accuracy: 0.9891
Epoch 2263/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0804 - accuracy: 0.9948
Epoch 2264/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.1197 - accuracy: 0.9922
Epoch 2265/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.1233 - accuracy: 0.9917
Epoch 2266/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.1115 - accuracy: 0.9927
Epoch 2267/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0806 - accuracy: 0.9943
Epoch 2268/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1155 - accuracy: 0.9917
Epoch 2269/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0881 - accuracy: 0.9943
Epoch 2270/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 70us/step - loss: 0.0562 - accuracy: 0.9964
Epoch 2338/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 2339/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.1120 - accuracy: 0.9927
Epoch 2340/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0963 - accuracy: 0.9933
Epoch 2341/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0886 - accuracy: 0.9938
Epoch 2342/6000
1287/1287 [==============================] - 0s 65us/step - loss: 0.1124 - accuracy: 0.9922
Epoch 2343/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 2344/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0801 - accuracy: 0.9948
Epoch 2345/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 2346/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 110us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 2413/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0641 - accuracy: 0.9959
Epoch 2414/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0963 - accuracy: 0.9933
Epoch 2415/6000
1287/1287 [==============================] - 0s 117us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 2416/6000
1287/1287 [==============================] - 0s 118us/step - loss: 0.0869 - accuracy: 0.9943
Epoch 2417/6000
1287/1287 [==============================] - 0s 141us/step - loss: 0.1090 - accuracy: 0.9922
Epoch 2418/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0954 - accuracy: 0.9927
Epoch 2419/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.1284 - accuracy: 0.9912
Epoch 2420/6000
1287/1287 [==============================] - 0s 121us/step - loss: 0.1482 - accuracy: 0.9902
Epoch 2421/6000
1287/1287 [========

1287/1287 [==============================] - 0s 114us/step - loss: 0.1197 - accuracy: 0.9922
Epoch 2488/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0911 - accuracy: 0.9933
Epoch 2489/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1126 - accuracy: 0.9927
Epoch 2490/6000
1287/1287 [==============================] - 0s 149us/step - loss: 0.0833 - accuracy: 0.9943
Epoch 2491/6000
1287/1287 [==============================] - 0s 64us/step - loss: 0.1122 - accuracy: 0.9922
Epoch 2492/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0919 - accuracy: 0.9938
Epoch 2493/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0975 - accuracy: 0.9933
Epoch 2494/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1270 - accuracy: 0.9912
Epoch 2495/6000
1287/1287 [==============================] - 0s 124us/step - loss: 0.0964 - accuracy: 0.9933
Epoch 2496/6000
1287/1287 [===========

1287/1287 [==============================] - 0s 81us/step - loss: 0.0886 - accuracy: 0.9938
Epoch 2563/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.0551 - accuracy: 0.9964
Epoch 2564/6000
1287/1287 [==============================] - 0s 105us/step - loss: 0.0803 - accuracy: 0.9948
Epoch 2565/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0644 - accuracy: 0.9953
Epoch 2566/6000
1287/1287 [==============================] - 0s 117us/step - loss: 0.0885 - accuracy: 0.9938
Epoch 2567/6000
1287/1287 [==============================] - 0s 127us/step - loss: 0.1040 - accuracy: 0.9933
Epoch 2568/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.1340 - accuracy: 0.9902
Epoch 2569/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1165 - accuracy: 0.9922
Epoch 2570/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.0478 - accuracy: 0.9969
Epoch 2571/6000
1287/1287 [=============

1287/1287 [==============================] - 0s 77us/step - loss: 0.0956 - accuracy: 0.9938
Epoch 2638/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.1434 - accuracy: 0.9907
Epoch 2639/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 2640/6000
1287/1287 [==============================] - 0s 142us/step - loss: 0.0967 - accuracy: 0.9933
Epoch 2641/6000
1287/1287 [==============================] - 0s 141us/step - loss: 0.1100 - accuracy: 0.9922
Epoch 2642/6000
1287/1287 [==============================] - 0s 141us/step - loss: 0.0884 - accuracy: 0.9938
Epoch 2643/6000
1287/1287 [==============================] - 0s 122us/step - loss: 0.0802 - accuracy: 0.9948
Epoch 2644/6000
1287/1287 [==============================] - 0s 97us/step - loss: 0.0480 - accuracy: 0.9969
Epoch 2645/6000
1287/1287 [==============================] - 0s 84us/step - loss: 0.0549 - accuracy: 0.9959
Epoch 2646/6000
1287/1287 [=============

1287/1287 [==============================] - 0s 70us/step - loss: 0.1448 - accuracy: 0.9902
Epoch 2713/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1645 - accuracy: 0.9891
Epoch 2714/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.1588 - accuracy: 0.9891
Epoch 2715/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 2716/6000
1287/1287 [==============================] - 0s 81us/step - loss: 0.0647 - accuracy: 0.9953
Epoch 2717/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0845 - accuracy: 0.9943
Epoch 2718/6000
1287/1287 [==============================] - 0s 89us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 2719/6000
1287/1287 [==============================] - 0s 94us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 2720/6000
1287/1287 [==============================] - 0s 85us/step - loss: 0.1143 - accuracy: 0.9922
Epoch 2721/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 81us/step - loss: 0.0809 - accuracy: 0.9943
Epoch 2788/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 2789/6000
1287/1287 [==============================] - 0s 82us/step - loss: 0.1200 - accuracy: 0.9922
Epoch 2790/6000
1287/1287 [==============================] - 0s 87us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 2791/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.0941 - accuracy: 0.9938
Epoch 2792/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 2793/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0819 - accuracy: 0.9943
Epoch 2794/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 2795/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.1358 - accuracy: 0.9912
Epoch 2796/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 95us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 2863/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.1047 - accuracy: 0.9927
Epoch 2864/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.0889 - accuracy: 0.9938
Epoch 2865/6000
1287/1287 [==============================] - 0s 117us/step - loss: 0.1515 - accuracy: 0.9902
Epoch 2866/6000
1287/1287 [==============================] - 0s 91us/step - loss: 0.0977 - accuracy: 0.9927
Epoch 2867/6000
1287/1287 [==============================] - 0s 92us/step - loss: 0.0806 - accuracy: 0.9943
Epoch 2868/6000
1287/1287 [==============================] - 0s 78us/step - loss: 0.0968 - accuracy: 0.9933
Epoch 2869/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0729 - accuracy: 0.9948
Epoch 2870/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0647 - accuracy: 0.9953
Epoch 2871/6000
1287/1287 [===============

1287/1287 [==============================] - 0s 105us/step - loss: 0.1162 - accuracy: 0.9922
Epoch 2938/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1115 - accuracy: 0.9927
Epoch 2939/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.1356 - accuracy: 0.9912
Epoch 2940/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 2941/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1043 - accuracy: 0.9933
Epoch 2942/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 2943/6000
1287/1287 [==============================] - 0s 106us/step - loss: 0.1406 - accuracy: 0.9907
Epoch 2944/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.1036 - accuracy: 0.9933
Epoch 2945/6000
1287/1287 [==============================] - 0s 105us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 2946/6000
1287/1287 [========

1287/1287 [==============================] - 0s 112us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 3013/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 3014/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 3015/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.1199 - accuracy: 0.9922
Epoch 3016/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1125 - accuracy: 0.9927
Epoch 3017/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0441 - accuracy: 0.9964
Epoch 3018/6000
1287/1287 [==============================] - 0s 97us/step - loss: 0.1182 - accuracy: 0.9917
Epoch 3019/6000
1287/1287 [==============================] - 0s 85us/step - loss: 0.1587 - accuracy: 0.9896
Epoch 3020/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 3021/6000
1287/1287 [==========

1287/1287 [==============================] - 0s 124us/step - loss: 0.0778 - accuracy: 0.9938
Epoch 3088/6000
1287/1287 [==============================] - 0s 127us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 3089/6000
1287/1287 [==============================] - 0s 141us/step - loss: 0.0731 - accuracy: 0.9943
Epoch 3090/6000
1287/1287 [==============================] - 0s 144us/step - loss: 0.1115 - accuracy: 0.9927
Epoch 3091/6000
1287/1287 [==============================] - 0s 146us/step - loss: 0.0682 - accuracy: 0.9953
Epoch 3092/6000
1287/1287 [==============================] - 0s 140us/step - loss: 0.0900 - accuracy: 0.9938
Epoch 3093/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.1204 - accuracy: 0.9917
Epoch 3094/6000
1287/1287 [==============================] - 0s 137us/step - loss: 0.0638 - accuracy: 0.9959
Epoch 3095/6000
1287/1287 [==============================] - 0s 140us/step - loss: 0.1122 - accuracy: 0.9922
Epoch 3096/6000
1287/1287 [========

1287/1287 [==============================] - 0s 121us/step - loss: 0.1044 - accuracy: 0.9933
Epoch 3163/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1218 - accuracy: 0.9917
Epoch 3164/6000
1287/1287 [==============================] - 0s 82us/step - loss: 0.0423 - accuracy: 0.9964
Epoch 3165/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1085 - accuracy: 0.9922
Epoch 3166/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0935 - accuracy: 0.9933
Epoch 3167/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0866 - accuracy: 0.9943
Epoch 3168/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0878 - accuracy: 0.9943
Epoch 3169/6000
1287/1287 [==============================] - 0s 63us/step - loss: 0.0855 - accuracy: 0.9938
Epoch 3170/6000
1287/1287 [==============================] - 0s 55us/step - loss: 0.0937 - accuracy: 0.9938
Epoch 3171/6000
1287/1287 [===============

1287/1287 [==============================] - 0s 140us/step - loss: 0.0406 - accuracy: 0.9969
Epoch 3238/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.0985 - accuracy: 0.9933
Epoch 3239/6000
1287/1287 [==============================] - 0s 120us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 3240/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.0800 - accuracy: 0.9948
Epoch 3241/6000
1287/1287 [==============================] - 0s 117us/step - loss: 0.0890 - accuracy: 0.9938
Epoch 3242/6000
1287/1287 [==============================] - 0s 120us/step - loss: 0.0823 - accuracy: 0.9933
Epoch 3243/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 3244/6000
1287/1287 [==============================] - 0s 125us/step - loss: 0.1286 - accuracy: 0.9912
Epoch 3245/6000
1287/1287 [==============================] - 0s 120us/step - loss: 0.1036 - accuracy: 0.9933
Epoch 3246/6000
1287/1287 [========

1287/1287 [==============================] - 0s 143us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 3313/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.0983 - accuracy: 0.9922
Epoch 3314/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.1570 - accuracy: 0.9891
Epoch 3315/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.0522 - accuracy: 0.9964
Epoch 3316/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.1038 - accuracy: 0.9933
Epoch 3317/6000
1287/1287 [==============================] - 0s 135us/step - loss: 0.0571 - accuracy: 0.9953
Epoch 3318/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0878 - accuracy: 0.9943
Epoch 3319/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 3320/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0560 - accuracy: 0.9964
Epoch 3321/6000
1287/1287 [========

1287/1287 [==============================] - 0s 136us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 3388/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0325 - accuracy: 0.9979
Epoch 3389/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 3390/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0973 - accuracy: 0.9927
Epoch 3391/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.0637 - accuracy: 0.9959
Epoch 3392/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.0911 - accuracy: 0.9938
Epoch 3393/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.0890 - accuracy: 0.9938
Epoch 3394/6000
1287/1287 [==============================] - 0s 137us/step - loss: 0.0773 - accuracy: 0.9948
Epoch 3395/6000
1287/1287 [==============================] - 0s 128us/step - loss: 0.0889 - accuracy: 0.9938
Epoch 3396/6000
1287/1287 [========

1287/1287 [==============================] - 0s 131us/step - loss: 0.0510 - accuracy: 0.9959
Epoch 3463/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 3464/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0559 - accuracy: 0.9964
Epoch 3465/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 3466/6000
1287/1287 [==============================] - 0s 135us/step - loss: 0.0967 - accuracy: 0.9933
Epoch 3467/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 3468/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.0960 - accuracy: 0.9938
Epoch 3469/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0402 - accuracy: 0.9974
Epoch 3470/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0416 - accuracy: 0.9964
Epoch 3471/6000
1287/1287 [========

Epoch 3537/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.0896 - accuracy: 0.9933
Epoch 3538/6000
1287/1287 [==============================] - 0s 140us/step - loss: 0.1199 - accuracy: 0.9922
Epoch 3539/6000
1287/1287 [==============================] - 0s 127us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 3540/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.1001 - accuracy: 0.9922
Epoch 3541/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0907 - accuracy: 0.9933
Epoch 3542/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.0724 - accuracy: 0.9948
Epoch 3543/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.0958 - accuracy: 0.9938
Epoch 3544/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.1010 - accuracy: 0.9927
Epoch 3545/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.1043 - accuracy: 0.9927
Epoch 3546/6000
128

1287/1287 [==============================] - 0s 136us/step - loss: 0.0884 - accuracy: 0.9938
Epoch 3613/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0878 - accuracy: 0.9943
Epoch 3614/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.1036 - accuracy: 0.9933
Epoch 3615/6000
1287/1287 [==============================] - 0s 145us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 3616/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.0571 - accuracy: 0.9959
Epoch 3617/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0480 - accuracy: 0.9969
Epoch 3618/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0868 - accuracy: 0.9943
Epoch 3619/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.1285 - accuracy: 0.9912
Epoch 3620/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0558 - accuracy: 0.9964
Epoch 3621/6000
1287/1287 [========

Epoch 3687/6000
1287/1287 [==============================] - 0s 140us/step - loss: 0.1129 - accuracy: 0.9922
Epoch 3688/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0728 - accuracy: 0.9953
Epoch 3689/6000
1287/1287 [==============================] - 0s 127us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 3690/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0806 - accuracy: 0.9943
Epoch 3691/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.1039 - accuracy: 0.9933
Epoch 3692/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0965 - accuracy: 0.9933
Epoch 3693/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 3694/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 3695/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.1037 - accuracy: 0.9933
Epoch 3696/6000
128

1287/1287 [==============================] - 0s 133us/step - loss: 0.1520 - accuracy: 0.9902
Epoch 3763/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0487 - accuracy: 0.9964
Epoch 3764/6000
1287/1287 [==============================] - 0s 135us/step - loss: 0.0645 - accuracy: 0.9953
Epoch 3765/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.1154 - accuracy: 0.9917
Epoch 3766/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 3767/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.1279 - accuracy: 0.9917
Epoch 3768/6000
1287/1287 [==============================] - 0s 137us/step - loss: 0.1276 - accuracy: 0.9917
Epoch 3769/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.1057 - accuracy: 0.9922
Epoch 3770/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0887 - accuracy: 0.9938
Epoch 3771/6000
1287/1287 [========

1287/1287 [==============================] - 0s 132us/step - loss: 0.0959 - accuracy: 0.9938
Epoch 3838/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.1070 - accuracy: 0.9917
Epoch 3839/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.1444 - accuracy: 0.9902
Epoch 3840/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.1952 - accuracy: 0.9870
Epoch 3841/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.1270 - accuracy: 0.9912
Epoch 3842/6000
1287/1287 [==============================] - 0s 166us/step - loss: 0.1117 - accuracy: 0.9927
Epoch 3843/6000
1287/1287 [==============================] - 0s 123us/step - loss: 0.1276 - accuracy: 0.9917
Epoch 3844/6000
1287/1287 [==============================] - 0s 116us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 3845/6000
1287/1287 [==============================] - 0s 126us/step - loss: 0.1515 - accuracy: 0.9902
Epoch 3846/6000
1287/1287 [========

1287/1287 [==============================] - 0s 133us/step - loss: 0.0637 - accuracy: 0.9959
Epoch 3913/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.1040 - accuracy: 0.9933
Epoch 3914/6000
1287/1287 [==============================] - 0s 128us/step - loss: 0.1196 - accuracy: 0.9922
Epoch 3915/6000
1287/1287 [==============================] - 0s 158us/step - loss: 0.0878 - accuracy: 0.99430s - loss: 0.0742 - accuracy: 0.
Epoch 3916/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 3917/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.0878 - accuracy: 0.9943
Epoch 3918/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.1328 - accuracy: 0.9912
Epoch 3919/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 3920/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.0959 - accuracy: 0.9938
Epo

1287/1287 [==============================] - 0s 132us/step - loss: 0.1118 - accuracy: 0.9927
Epoch 3988/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0486 - accuracy: 0.9964
Epoch 3989/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.0741 - accuracy: 0.9943
Epoch 3990/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.0805 - accuracy: 0.9943
Epoch 3991/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.1087 - accuracy: 0.9927
Epoch 3992/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.1127 - accuracy: 0.9922
Epoch 3993/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.0745 - accuracy: 0.9938
Epoch 3994/6000
1287/1287 [==============================] - 0s 128us/step - loss: 0.0559 - accuracy: 0.9964
Epoch 3995/6000
1287/1287 [==============================] - 0s 133us/step - loss: 0.0778 - accuracy: 0.9943
Epoch 3996/6000
1287/1287 [========

1287/1287 [==============================] - 0s 72us/step - loss: 0.1133 - accuracy: 0.9917
Epoch 4063/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0637 - accuracy: 0.9959
Epoch 4064/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.1221 - accuracy: 0.9912
Epoch 4065/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 4066/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.0718 - accuracy: 0.9953
Epoch 4067/6000
1287/1287 [==============================] - 0s 136us/step - loss: 0.0972 - accuracy: 0.9927
Epoch 4068/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0648 - accuracy: 0.9953
Epoch 4069/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.0882 - accuracy: 0.9943
Epoch 4070/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.1146 - accuracy: 0.9917
Epoch 4071/6000
1287/1287 [===========

1287/1287 [==============================] - 0s 74us/step - loss: 0.0956 - accuracy: 0.9938
Epoch 4138/6000
1287/1287 [==============================] - 0s 125us/step - loss: 0.1052 - accuracy: 0.9927
Epoch 4139/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.1289 - accuracy: 0.9912
Epoch 4140/6000
1287/1287 [==============================] - 0s 142us/step - loss: 0.0837 - accuracy: 0.9943
Epoch 4141/6000
1287/1287 [==============================] - 0s 140us/step - loss: 0.1037 - accuracy: 0.9933
Epoch 4142/6000
1287/1287 [==============================] - 0s 134us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 4143/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.0966 - accuracy: 0.9933
Epoch 4144/6000
1287/1287 [==============================] - 0s 129us/step - loss: 0.1200 - accuracy: 0.9922
Epoch 4145/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.0682 - accuracy: 0.9953
Epoch 4146/6000
1287/1287 [=========

1287/1287 [==============================] - 0s 151us/step - loss: 0.0584 - accuracy: 0.9953
Epoch 4213/6000
1287/1287 [==============================] - 0s 166us/step - loss: 0.0817 - accuracy: 0.9938
Epoch 4214/6000
1287/1287 [==============================] - 0s 151us/step - loss: 0.0727 - accuracy: 0.9948
Epoch 4215/6000
1287/1287 [==============================] - 0s 159us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 4216/6000
1287/1287 [==============================] - 0s 156us/step - loss: 0.0820 - accuracy: 0.9938
Epoch 4217/6000
1287/1287 [==============================] - 0s 156us/step - loss: 0.0575 - accuracy: 0.9959
Epoch 4218/6000
1287/1287 [==============================] - 0s 142us/step - loss: 0.0886 - accuracy: 0.9938
Epoch 4219/6000
1287/1287 [==============================] - 0s 144us/step - loss: 0.0561 - accuracy: 0.9964
Epoch 4220/6000
1287/1287 [==============================] - 0s 139us/step - loss: 0.0887 - accuracy: 0.9938
Epoch 4221/6000
1287/1287 [========

1287/1287 [==============================] - 0s 145us/step - loss: 0.0967 - accuracy: 0.9933
Epoch 4288/6000
1287/1287 [==============================] - 0s 141us/step - loss: 0.1038 - accuracy: 0.9933
Epoch 4289/6000
1287/1287 [==============================] - 0s 143us/step - loss: 0.1200 - accuracy: 0.9922
Epoch 4290/6000
1287/1287 [==============================] - 0s 163us/step - loss: 0.1368 - accuracy: 0.9907
Epoch 4291/6000
1287/1287 [==============================] - 0s 153us/step - loss: 0.0732 - accuracy: 0.9948
Epoch 4292/6000
1287/1287 [==============================] - 0s 152us/step - loss: 0.0889 - accuracy: 0.9938
Epoch 4293/6000
1287/1287 [==============================] - 0s 142us/step - loss: 0.0972 - accuracy: 0.9933
Epoch 4294/6000
1287/1287 [==============================] - 0s 93us/step - loss: 0.1038 - accuracy: 0.9933
Epoch 4295/6000
1287/1287 [==============================] - 0s 94us/step - loss: 0.0882 - accuracy: 0.9943
Epoch 4296/6000
1287/1287 [==========

1287/1287 [==============================] - 0s 73us/step - loss: 0.0960 - accuracy: 0.9938
Epoch 4363/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0638 - accuracy: 0.9959
Epoch 4364/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0718 - accuracy: 0.9953
Epoch 4365/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1120 - accuracy: 0.9927
Epoch 4366/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1016 - accuracy: 0.9933
Epoch 4367/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1177 - accuracy: 0.9917
Epoch 4368/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0324 - accuracy: 0.9979
Epoch 4369/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.0902 - accuracy: 0.9938
Epoch 4370/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.0489 - accuracy: 0.9964
Epoch 4371/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 75us/step - loss: 0.1118 - accuracy: 0.9927
Epoch 4438/6000
1287/1287 [==============================] - 0s 78us/step - loss: 0.1037 - accuracy: 0.9933
Epoch 4439/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 4440/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.0822 - accuracy: 0.9938
Epoch 4441/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.1044 - accuracy: 0.9927
Epoch 4442/6000
1287/1287 [==============================] - 0s 79us/step - loss: 0.1118 - accuracy: 0.9927
Epoch 4443/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 4444/6000
1287/1287 [==============================] - 0s 81us/step - loss: 0.0626 - accuracy: 0.9959
Epoch 4445/6000
1287/1287 [==============================] - 0s 78us/step - loss: 0.0486 - accuracy: 0.9969
Epoch 4446/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 77us/step - loss: 0.0731 - accuracy: 0.9948
Epoch 4513/6000
1287/1287 [==============================] - 0s 81us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 4514/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0959 - accuracy: 0.9938
Epoch 4515/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0813 - accuracy: 0.9943
Epoch 4516/6000
1287/1287 [==============================] - 0s 81us/step - loss: 0.0924 - accuracy: 0.9938
Epoch 4517/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 4518/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 4519/6000
1287/1287 [==============================] - 0s 95us/step - loss: 0.1040 - accuracy: 0.9933
Epoch 4520/6000
1287/1287 [==============================] - 0s 121us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 4521/6000
1287/1287 [================

1287/1287 [==============================] - 0s 116us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 4588/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.1449 - accuracy: 0.9902
Epoch 4589/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.1442 - accuracy: 0.9902
Epoch 4590/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.1127 - accuracy: 0.9922
Epoch 4591/6000
1287/1287 [==============================] - 0s 118us/step - loss: 0.0887 - accuracy: 0.9938
Epoch 4592/6000
1287/1287 [==============================] - 0s 126us/step - loss: 0.1047 - accuracy: 0.9927
Epoch 4593/6000
1287/1287 [==============================] - 0s 126us/step - loss: 0.1200 - accuracy: 0.9922
Epoch 4594/6000
1287/1287 [==============================] - 0s 138us/step - loss: 0.1436 - accuracy: 0.9907
Epoch 4595/6000
1287/1287 [==============================] - 0s 132us/step - loss: 0.1675 - accuracy: 0.9891
Epoch 4596/6000
1287/1287 [========

1287/1287 [==============================] - 0s 65us/step - loss: 0.0648 - accuracy: 0.9953
Epoch 4663/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0416 - accuracy: 0.9969
Epoch 4664/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0800 - accuracy: 0.9948
Epoch 4665/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0399 - accuracy: 0.9974
Epoch 4666/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0718 - accuracy: 0.9953
Epoch 4667/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0481 - accuracy: 0.9969
Epoch 4668/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.1117 - accuracy: 0.9922
Epoch 4669/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0570 - accuracy: 0.9959
Epoch 4670/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0717 - accuracy: 0.9953
Epoch 4671/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 110us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 4738/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0830 - accuracy: 0.9938
Epoch 4739/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 4740/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0809 - accuracy: 0.9943
Epoch 4741/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0320 - accuracy: 0.9979
Epoch 4742/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.1197 - accuracy: 0.9922
Epoch 4743/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0321 - accuracy: 0.9979
Epoch 4744/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.1450 - accuracy: 0.9902
Epoch 4745/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.0509 - accuracy: 0.9964
Epoch 4746/6000
1287/1287 [========

1287/1287 [==============================] - 0s 132us/step - loss: 0.0949 - accuracy: 0.9938
Epoch 4813/6000
1287/1287 [==============================] - 0s 137us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 4814/6000
1287/1287 [==============================] - 0s 120us/step - loss: 0.0640 - accuracy: 0.9959
Epoch 4815/6000
1287/1287 [==============================] - 0s 119us/step - loss: 0.0638 - accuracy: 0.9959
Epoch 4816/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.0629 - accuracy: 0.9959
Epoch 4817/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0936 - accuracy: 0.9938
Epoch 4818/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1070 - accuracy: 0.9922
Epoch 4819/6000
1287/1287 [==============================] - 0s 96us/step - loss: 0.1515 - accuracy: 0.9902
Epoch 4820/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.1560 - accuracy: 0.9891
Epoch 4821/6000
1287/1287 [===========

1287/1287 [==============================] - 0s 70us/step - loss: 0.0559 - accuracy: 0.9964
Epoch 4888/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0570 - accuracy: 0.9959
Epoch 4889/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1015 - accuracy: 0.9933
Epoch 4890/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0569 - accuracy: 0.9959
Epoch 4891/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 4892/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 4893/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0641 - accuracy: 0.9959
Epoch 4894/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0096 - accuracy: 0.9990
Epoch 4895/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0881 - accuracy: 0.9943
Epoch 4896/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 68us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 4964/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0688 - accuracy: 0.9953
Epoch 4965/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0797 - accuracy: 0.9948
Epoch 4966/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0410 - accuracy: 0.9969
Epoch 4967/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 4968/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0730 - accuracy: 0.9948
Epoch 4969/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0831 - accuracy: 0.9943
Epoch 4970/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0803 - accuracy: 0.9943
Epoch 4971/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0979 - accuracy: 0.9927
Epoch 4972/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 67us/step - loss: 0.0817 - accuracy: 0.9938
Epoch 5040/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0970 - accuracy: 0.9933
Epoch 5041/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0576 - accuracy: 0.9959
Epoch 5042/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0957 - accuracy: 0.9938
Epoch 5043/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 5044/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0502 - accuracy: 0.9959
Epoch 5045/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0320 - accuracy: 0.9979
Epoch 5046/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0570 - accuracy: 0.9959
Epoch 5047/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0573 - accuracy: 0.9959
Epoch 5048/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 69us/step - loss: 0.0326 - accuracy: 0.9979
Epoch 5115/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0824 - accuracy: 0.9938
Epoch 5116/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0640 - accuracy: 0.9959
Epoch 5117/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0572 - accuracy: 0.9959
Epoch 5118/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0637 - accuracy: 0.9959
Epoch 5119/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0887 - accuracy: 0.9938
Epoch 5120/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0819 - accuracy: 0.9938
Epoch 5121/6000
1287/1287 [==============================] - 0s 80us/step - loss: 0.0728 - accuracy: 0.9948
Epoch 5122/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0558 - accuracy: 0.9964
Epoch 5123/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 109us/step - loss: 0.1197 - accuracy: 0.9922
Epoch 5190/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0724 - accuracy: 0.9948
Epoch 5191/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.1058 - accuracy: 0.9927
Epoch 5192/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0799 - accuracy: 0.9948
Epoch 5193/6000
1287/1287 [==============================] - 0s 107us/step - loss: 0.0719 - accuracy: 0.9953
Epoch 5194/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0672 - accuracy: 0.9953
Epoch 5195/6000
1287/1287 [==============================] - 0s 115us/step - loss: 0.0649 - accuracy: 0.9953
Epoch 5196/6000
1287/1287 [==============================] - 0s 105us/step - loss: 0.0338 - accuracy: 0.9969
Epoch 5197/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0478 - accuracy: 0.9969
Epoch 5198/6000
1287/1287 [========

1287/1287 [==============================] - 0s 122us/step - loss: 0.0331 - accuracy: 0.9974
Epoch 5265/6000
1287/1287 [==============================] - 0s 125us/step - loss: 0.0714 - accuracy: 0.9948
Epoch 5266/6000
1287/1287 [==============================] - 0s 112us/step - loss: 0.0559 - accuracy: 0.9964
Epoch 5267/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0718 - accuracy: 0.9953
Epoch 5268/6000
1287/1287 [==============================] - 0s 118us/step - loss: 0.0722 - accuracy: 0.9953
Epoch 5269/6000
1287/1287 [==============================] - 0s 119us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 5270/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.0450 - accuracy: 0.9969
Epoch 5271/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0647 - accuracy: 0.9953
Epoch 5272/6000
1287/1287 [==============================] - 0s 114us/step - loss: 0.0492 - accuracy: 0.9964
Epoch 5273/6000
1287/1287 [========

1287/1287 [==============================] - 0s 120us/step - loss: 0.0957 - accuracy: 0.9938
Epoch 5340/6000
1287/1287 [==============================] - 0s 102us/step - loss: 0.0792 - accuracy: 0.9943
Epoch 5341/6000
1287/1287 [==============================] - 0s 122us/step - loss: 0.0648 - accuracy: 0.9953
Epoch 5342/6000
1287/1287 [==============================] - 0s 113us/step - loss: 0.0642 - accuracy: 0.9959
Epoch 5343/6000
1287/1287 [==============================] - 0s 121us/step - loss: 0.0642 - accuracy: 0.9959
Epoch 5344/6000
1287/1287 [==============================] - 0s 110us/step - loss: 0.0956 - accuracy: 0.9938
Epoch 5345/6000
1287/1287 [==============================] - 0s 109us/step - loss: 0.0884 - accuracy: 0.9943
Epoch 5346/6000
1287/1287 [==============================] - 0s 111us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5347/6000
1287/1287 [==============================] - 0s 108us/step - loss: 0.0408 - accuracy: 0.9969
Epoch 5348/6000
1287/1287 [========

1287/1287 [==============================] - 0s 72us/step - loss: 0.0956 - accuracy: 0.9938
Epoch 5415/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0721 - accuracy: 0.9953
Epoch 5416/6000
1287/1287 [==============================] - 0s 85us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 5417/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0953 - accuracy: 0.9938
Epoch 5418/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.0964 - accuracy: 0.9933
Epoch 5419/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.1195 - accuracy: 0.9922
Epoch 5420/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5421/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0566 - accuracy: 0.9959
Epoch 5422/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0568 - accuracy: 0.9964
Epoch 5423/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 68us/step - loss: 0.1357 - accuracy: 0.9912
Epoch 5491/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0821 - accuracy: 0.9938
Epoch 5492/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0511 - accuracy: 0.9959
Epoch 5493/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0580 - accuracy: 0.9953
Epoch 5494/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5495/6000
1287/1287 [==============================] - 0s 65us/step - loss: 0.0879 - accuracy: 0.9943
Epoch 5496/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0798 - accuracy: 0.9948
Epoch 5497/6000
1287/1287 [==============================] - 0s 65us/step - loss: 0.1128 - accuracy: 0.9922
Epoch 5498/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.0720 - accuracy: 0.9953
Epoch 5499/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 72us/step - loss: 0.0728 - accuracy: 0.9948
Epoch 5567/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0486 - accuracy: 0.9969
Epoch 5568/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0560 - accuracy: 0.9964
Epoch 5569/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0244 - accuracy: 0.9984
Epoch 5570/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0564 - accuracy: 0.9964
Epoch 5571/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0573 - accuracy: 0.9953
Epoch 5572/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0729 - accuracy: 0.9948
Epoch 5573/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0409 - accuracy: 0.9969
Epoch 5574/6000
1287/1287 [==============================] - 0s 66us/step - loss: 0.1202 - accuracy: 0.9922
Epoch 5575/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 70us/step - loss: 0.1115 - accuracy: 0.9927
Epoch 5643/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0572 - accuracy: 0.9959
Epoch 5644/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0501 - accuracy: 0.9959
Epoch 5645/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0640 - accuracy: 0.9959
Epoch 5646/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0244 - accuracy: 0.9984
Epoch 5647/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0321 - accuracy: 0.9979
Epoch 5648/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0495 - accuracy: 0.9964
Epoch 5649/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.1020 - accuracy: 0.9933
Epoch 5650/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0733 - accuracy: 0.9948
Epoch 5651/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 69us/step - loss: 0.0559 - accuracy: 0.9964
Epoch 5718/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0650 - accuracy: 0.9953
Epoch 5719/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0504 - accuracy: 0.9959
Epoch 5720/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0879 - accuracy: 0.9943
Epoch 5721/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0643 - accuracy: 0.9959
Epoch 5722/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0478 - accuracy: 0.9969
Epoch 5723/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0959 - accuracy: 0.9938
Epoch 5724/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0249 - accuracy: 0.9979
Epoch 5725/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0879 - accuracy: 0.9943
Epoch 5726/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 74us/step - loss: 0.0652 - accuracy: 0.9953
Epoch 5793/6000
1287/1287 [==============================] - 0s 77us/step - loss: 0.0646 - accuracy: 0.9953
Epoch 5794/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0562 - accuracy: 0.9964
Epoch 5795/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0967 - accuracy: 0.9933
Epoch 5796/6000
1287/1287 [==============================] - 0s 78us/step - loss: 0.0793 - accuracy: 0.9933
Epoch 5797/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0961 - accuracy: 0.9938
Epoch 5798/6000
1287/1287 [==============================] - 0s 76us/step - loss: 0.0725 - accuracy: 0.9953
Epoch 5799/6000
1287/1287 [==============================] - 0s 131us/step - loss: 0.0639 - accuracy: 0.9959
Epoch 5800/6000
1287/1287 [==============================] - 0s 130us/step - loss: 0.0569 - accuracy: 0.9959
Epoch 5801/6000
1287/1287 [===============

1287/1287 [==============================] - 0s 65us/step - loss: 0.0718 - accuracy: 0.9953
Epoch 5868/6000
1287/1287 [==============================] - 0s 65us/step - loss: 0.0897 - accuracy: 0.9938
Epoch 5869/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0479 - accuracy: 0.9969
Epoch 5870/6000
1287/1287 [==============================] - 0s 71us/step - loss: 0.0741 - accuracy: 0.9943
Epoch 5871/6000
1287/1287 [==============================] - 0s 78us/step - loss: 0.0879 - accuracy: 0.9943
Epoch 5872/6000
1287/1287 [==============================] - 0s 74us/step - loss: 0.0641 - accuracy: 0.9959
Epoch 5873/6000
1287/1287 [==============================] - 0s 75us/step - loss: 0.0242 - accuracy: 0.9984
Epoch 5874/6000
1287/1287 [==============================] - 0s 67us/step - loss: 0.0640 - accuracy: 0.9959
Epoch 5875/6000
1287/1287 [==============================] - 0s 72us/step - loss: 0.0410 - accuracy: 0.9969
Epoch 5876/6000
1287/1287 [=================

1287/1287 [==============================] - 0s 69us/step - loss: 0.0491 - accuracy: 0.9964
Epoch 5944/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5945/6000
1287/1287 [==============================] - 0s 68us/step - loss: 0.0649 - accuracy: 0.9953
Epoch 5946/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0626 - accuracy: 0.9959
Epoch 5947/6000
1287/1287 [==============================] - 0s 73us/step - loss: 0.0876 - accuracy: 0.9943
Epoch 5948/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5949/6000
1287/1287 [==============================] - 0s 69us/step - loss: 0.0650 - accuracy: 0.9953
Epoch 5950/6000
1287/1287 [==============================] - 0s 70us/step - loss: 0.0651 - accuracy: 0.9953
Epoch 5951/6000
1287/1287 [==============================] - 0s 65us/step - loss: 0.0649 - accuracy: 0.9953
Epoch 5952/6000
1287/1287 [=================

In [12]:
score=model.evaluate(x_test,y_test,batch_size=64,)

1332/1332 [==============================] - 0s 64us/step


In [13]:
model.metrics_names

['loss', 'accuracy']

In [14]:
score

[6.709018849037789, 0.5625626444816589]

In [16]:
y_pred=model.predict(x_test[:],batch_size=None, verbose=0,steps=None)
print(y_pred)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [18]:
df = pd.DataFrame(y_pred)
print(df)
df.to_excel(r'C:/Users/hp/Desktop/NN1_6000.xlsx', index = False)
df.head()

        0    1    2
0     1.0  0.0  0.0
1     1.0  0.0  0.0
2     0.0  0.0  1.0
3     1.0  0.0  0.0
4     1.0  0.0  0.0
...   ...  ...  ...
1327  1.0  0.0  0.0
1328  1.0  0.0  0.0
1329  1.0  0.0  0.0
1330  0.0  1.0  0.0
1331  1.0  0.0  0.0

[1332 rows x 3 columns]


0    1    2
0  1.0  0.0  0.0
1  1.0  0.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0
4  1.0  0.0  0.0